#!/usr/bin/env bash
# Guided RHEL 9 → RHEL 10 LEAPP demo using redhat.leapp (via ansible-navigator EE)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"
# shellcheck source=../lab/common.sh
source "${REPO_ROOT}/lab/common.sh"

LIMIT="leapp-rhel9"
PROFILE="rhel9"
RUN_PB="${REPO_ROOT}/scripts/run-with-navigator.sh"

echo "=== LEAPP demo: RHEL 9 → RHEL 10 (CDN) ==="

if ! virsh --connect "${LIBVIRT_URI}" dominfo leapp-rhel9 >/dev/null 2>&1; then
  echo "==> Creating leapp-rhel9"
  ./lab/create-vm.sh "${PROFILE}"
else
  echo "==> leapp-rhel9 already exists; refreshing inventory"
  ./scripts/inventory-from-libvirt.sh
fi

run_pb() {
  local pb="$1"
  echo
  "${RUN_PB}" "${pb}" "${LIMIT}"
}

run_pb playbooks/00-prepare.yml
run_pb playbooks/01-analysis.yml

GUEST_IP="$(guest_ipv4 "${LIMIT}")"
echo
echo "Review the Leapp report on the guest:"
echo "  ssh ${VM_USER}@${GUEST_IP} 'sudo less /var/log/leapp/leapp-report.txt'"
echo "Also check host_vars generated by the analysis role (often under playbooks/host_vars/)."
read -r -p "Press Enter to continue with remediation..."

run_pb playbooks/02-remediate.yml
run_pb playbooks/01-analysis.yml

echo
read -r -p "If inhibitors are clear, press Enter to start the upgrade (long-running, reboots expected)..."

run_pb playbooks/03-upgrade.yml
run_pb playbooks/99-verify.yml

echo
echo "Demo complete for ${LIMIT}."
