#!/usr/bin/env bash
# Resolve libvirt guest IPv4 addresses into inventory/lab.generated.yml
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=../lab/common.sh
source "${REPO_ROOT}/lab/common.sh"

OUT="${REPO_ROOT}/inventory/lab.generated.yml"
DOMAINS=(leapp-rhel8 leapp-rhel9)

entries=()
for name in "${DOMAINS[@]}"; do
  if ! virsh --connect "${LIBVIRT_URI}" dominfo "${name}" >/dev/null 2>&1; then
    continue
  fi
  ip="$(guest_ipv4 "${name}")"
  if [[ -z "${ip}" ]]; then
    echo "WARNING: ${name} has no IPv4 lease yet" >&2
    continue
  fi
  entries+=("${name}|${ip}")
done

{
  echo "---"
  echo "# Generated by scripts/inventory-from-libvirt.sh — do not edit by hand"
  echo "all:"
  echo "  hosts:"
  if [[ "${#entries[@]}" -eq 0 ]]; then
    echo "    {}"
  else
    for entry in "${entries[@]}"; do
      name="${entry%%|*}"
      ip="${entry##*|}"
      echo "    ${name}:"
      echo "      ansible_host: ${ip}"
      echo "      ansible_user: ${VM_USER}"
    done
  fi
} > "${OUT}"

# Normalize empty-hosts case to valid YAML
if [[ "${#entries[@]}" -eq 0 ]]; then
  cat > "${OUT}" <<'EOF'
---
# Generated by scripts/inventory-from-libvirt.sh — no running lab VMs found
all:
  hosts: {}
EOF
fi

echo "Wrote ${OUT}"
if [[ "${#entries[@]}" -gt 0 ]]; then
  for entry in "${entries[@]}"; do
    echo "  ${entry%%|*} -> ${entry##*|}"
  done
fi
