---
- name: LEAPP pre-upgrade analysis
  hosts: leapp_targets
  gather_facts: true
  become: true
  tasks:
    - name: Run redhat.leapp.analysis
      ansible.builtin.import_role:
        name: redhat.leapp.analysis
      vars:
        leapp_preupg_opts: "{{ leapp_upgrade_opts | default(omit) }}"
