---
- name: LEAPP in-place OS upgrade
  hosts: leapp_targets
  gather_facts: true
  become: true
  tasks:
    - name: Perform OS upgrade with infra.leapp.upgrade
      ansible.builtin.import_role:
        name: infra.leapp.upgrade
